// Add steps as necessary for accessing the software, post-configuration, and testing. Don’t include full usage instructions for your software, but add links to your product documentation for that information.
//Should any sections not be applicable, remove them

== Test the deployment
// If steps are required to test the deployment, add them here. If not, remove the heading

. Go to the Lex console. Search for the bot name you provided as parameter when launching the stack. By default it's called ‘covid_nineteen_bot’.
. Test the Lex bot intents by typing ‘Hi’. You should receive a response as _‘Amazon Lex: Hello! I am the COVID-19 Rapid Response Bot! You can ask me questions related to COVID-19. As a disclaimer, I'm not responsible for providing professional medical advice, diagnosis or treatment. If you are experiencing life threatening emergency, please call 911. How can I help?’_
3.	Test the Kendra search capabilities and connection with Lex by typing _‘What preventive measures can I take?’_. You should receive a response as ‘On searching the Enterprise repository, I have found the following answer in the FAQs--Wash your hands often, avoid close contact with people and cover your mouth and nose with a cloth face cover when around people, monitor your health, clean and disinfect frequently touched surfaces daily.’

== Other useful information
//Provide any other information of interest to users, especially focusing on areas where AWS or cloud usage differs from on-premises usage.

You can use custom UIs or 3rd party products as a frontend for your users to interact with, and use the Lex ChatBot deployed in this Quick Start as a backend which connects with Amazon Kendra to answer user questions.