// Add steps as necessary for accessing the software, post-configuration, and testing. Don’t include full usage instructions for your software, but add links to your product documentation for that information.
//Should any sections not be applicable, remove them

== Test the deployment
// If steps are required to test the deployment, add them here. If not, remove the heading

. Go to the Amazon Lex console. Search for the chatbot name you provided as a parameter when launching the stack. By default, the name is  ‘self_service_lex_bot’.
. Test the Amazon Lex chatbot intents by typing ‘Hi’. You should receive the following response: _‘Amazon Lex: Hello! I am the COVID-19 Rapid Response Bot! You can ask me questions related to COVID-19. As a disclaimer, I'm not responsible for providing professional medical advice, diagnosis or treatment. If you are experiencing life threatening emergency, please call 911. How can I help?’_
. Test the Amazon Kendra search capabilities and connection with Amazon Lex by typing ‘What preventive measures can I take?’. You should receive the following response: _On searching the Enterprise repository, I have found the following answer in the FAQs. Wash your hands often, avoid close contact with people and cover your mouth and nose with a cloth face cover when around people, monitor your health, clean and disinfect frequently touched surfaces daily.’_

== Other useful information
//Provide any other information of interest to users, especially focusing on areas where AWS or cloud usage differs from on-premises usage.

You can use a custom user interface or third-party product as a front end for users to interact with and submit questions. As a back end, use the Amazon Lex chatbot that is deployed with this Quick Start to connect with Amazon Kendra to answer user questions.  